name: "[CI/A]"

on:
  workflow_dispatch:
  push:
    branches: 
      - feat/docker-image
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: "push docker image"
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3 
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE_ARN }}
          aws-region: us-east-1
          mask-aws-account-id: true

      - uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ECR_REPOSITORY }}  
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1.6.2
        with:
          mask-password: 'true'

      - name: Build Docker Image
        run: |
          IMAGE_NAME=${{ secrets.ECR_REPOSITORY }}:${{ github.sha }}
          pwd
          ls
          docker build -f ./Dockerfile --force-rm -t $IMAGE_NAME . 
  
      - name: Push Docker Image to ECR
        run: |
          IMAGE_NAME=${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_REPOSITORY }}:${{ github.sha }}
          docker push $IMAGE_NAME        
